services:
    db:
        container_name: postgres
        image: postgres:17
        ports:
            - "5432:5432"
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=stock
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
